
export const SIGNAL_R_REQUEST = 'SIGNAL_R_REQUEST';
export const SIGNAL_R_SUCCESS = 'SIGNAL_R_SUCCESS';
export const SIGNAL_R_SET_NOTIFICATION = 'SIGNAL_R_SET_NOTIFICATION';
export const SIGNAL_R_GET_NOTIFICATION = 'SIGNAL_R_GET_NOTIFICATION';
export const SIGNAL_R_FAILURE = 'SIGNAL_R_FAILURE';


export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAILURE = 'SEND_MESSAGE_FAILURE';